# vim:ft=ansible:ts=2:et:
---
- name: Add MongoDB Deb822 Repo
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
    # ignore invalid/expired signature
    trusted: yes
  loop: "{{ _mongos.deb822_repository | default([]) }}"

- name: Install MongoS
  ansible.builtin.apt:
    name: "{{ item.name }}={{ item.version }}"
    state: present
    update_cache: true
  with_items: "{{ _mongos.apt.packages }}"

- name: Create MongoDB Group
  ansible.builtin.group:
    name: "mongodb"
    system: yes
    state: present

- name: Create MongoDB User
  ansible.builtin.user:
    name: "mongodb"
    createhome: no
    system: yes
    group: mongodb
    state: present
    shell: /usr/sbin/nologin

- name: Install consul healthcheck helper
  ansible.builtin.copy:
    src: usr/local/bin/mongos-healthcheck.sh
    dest: /usr/local/bin/mongos-healthcheck.sh
    mode: "0755"

- name: Copy mongosh.conf
  ansible.builtin.copy:
    src: "etc/mongosh.conf"
    dest: "/etc/mongosh.conf"
    owner: root
    group: root
    mode: "0644"

- name: Create mongosh history reversal script
  ansible.builtin.copy:
    src: "usr/local/bin/mongosh-history-reverse.sh"
    dest: "/usr/local/bin/mongosh-history-reverse.sh"
    owner: root
    group: root
    mode: "0755"

- name: Install mongosh history reversal systemd units
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  loop:
    - etc/systemd/system/mongosh-history-reverse.service
    - etc/systemd/system/mongosh-history-reverse.timer

- name: Enable mongosh history reversal timer
  ansible.builtin.systemd:
    name: mongosh-history-reverse.timer
    enabled: true
    daemon_reload: true
