# vim:ft=ansible:ts=2:et:
---

- name: Install MongoDB package key
  ansible.builtin.get_url:
    url: "{{ _mongos.apt.key_url }}"
    dest: /etc/apt/trusted.gpg.d/mongodb.asc
    owner: root
    group: root
    mode: 0644

- name: Add MongoDB repository
  ansible.builtin.apt_repository:
    repo: "{{ _mongos.apt.repo_line }}"
    state: present

- name: Install MongoS
  ansible.builtin.apt:
    name: "{{ item.name }}={{ item.version }}"
    state: present
  with_items: "{{ _mongos.apt.packages }}"

- name: Create MongoDB Group
  ansible.builtin.group:
    name: "mongodb"
    system: yes
    state: present

- name: Create MongoDB User
  ansible.builtin.user:
    name: "mongodb"
    createhome: no
    system: yes
    group: mongodb
    state: present
    shell: /usr/sbin/nologin

- name: Install consul healthcheck helper
  ansible.builtin.copy:
    src: usr/local/bin/mongos-healthcheck.sh
    dest: /usr/local/bin/mongos-healthcheck.sh
    mode: "0755"
