# vim:ft=ansible:ts=2:et:
---
- name: Add MongoDB Deb822 Repo
  ansible.builtin.deb822_repository:
    name: "{{ item.name }}"
    types: deb
    uris: "{{ item.uris }}"
    suites: "{{ item.suites }}"
    components: "{{ item.components }}"
    signed_by: "{{ item.signed_by }}"
    # ignore invalid/expired signature
    trusted: yes
  loop: "{{ _mongos.deb822_repository | default([]) }}"

- name: Install MongoS
  ansible.builtin.apt:
    name: "{{ item.name }}={{ item.version }}"
    state: present
    update_cache: true
  with_items: "{{ _mongos.apt.packages }}"

- name: Create MongoDB Group
  ansible.builtin.group:
    name: "mongodb"
    system: yes
    state: present

- name: Create MongoDB User
  ansible.builtin.user:
    name: "mongodb"
    createhome: no
    system: yes
    group: mongodb
    state: present
    shell: /usr/sbin/nologin

- name: Install consul healthcheck helper
  ansible.builtin.copy:
    src: usr/local/bin/mongos-healthcheck.sh
    dest: /usr/local/bin/mongos-healthcheck.sh
    mode: "0755"
